# Generated by Django 5.2.14 on 2026-05-29 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('bandera_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['level', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multiple_choice', 'Opcion multiple'), ('fill_blank', 'Completar espacio'), ('translate', 'Traducir'), ('listen', 'Escuchar'), ('speak', 'Hablar')], default='multiple_choice', max_length=20)),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('respuesta_correcta', models.TextField()),
                ('puntos', models.IntegerField(default=10)),
                ('orden', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='catalog.lesson')),
            ],
            options={
                'ordering': ['lesson', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_cefr', models.CharField(blank=True, default='', max_length=5)),
                ('orden', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalog.language')),
            ],
            options={
                'ordering': ['language', 'orden'],
                'unique_together': {('language', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.level'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha_dias', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='catalog.language')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='catalog.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcto', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('completado_en', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='catalog.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completado_en'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('level', 'orden')},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_en', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catalog.level')),
            ],
            options={
                'ordering': ['-inscrito_en'],
                'unique_together': {('user', 'level')},
            },
        ),
    ]
